### ISSUE TITLE
pip install does not work for ifttt 0.2.9. Missing README.md

### ISSUE THREAD

**Issue by davecoutts** [newslynx/ifttt#1]
pip install does not work for ifttt 0.2.9
The README.md file is missing from https://pypi.python.org/packages/source/i/ifttt/ifttt-0.2.9.tar.gz

```
pip install ifttt
Collecting ifttt
  Using cached ifttt-0.2.9.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-e7PUeM/ifttt/setup.py", line 28, in <module>
        build()
      File "/tmp/pip-build-e7PUeM/ifttt/setup.py", line 18, in build
        long_description = readme('README.md'),
      File "/tmp/pip-build-e7PUeM/ifttt/setup.py", line 5, in readme
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-e7PUeM/ifttt/README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/tmp/pip-build-e7PUeM/ifttt/setup.py", line 28, in <module>

        build()

      File "/tmp/pip-build-e7PUeM/ifttt/setup.py", line 18, in build

        long_description = readme('README.md'),

      File "/tmp/pip-build-e7PUeM/ifttt/setup.py", line 5, in readme

        return open(os.path.join(os.path.dirname(__file__), fname)).read()

    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-e7PUeM/ifttt/README.md'

```

**Comment by abelsonlive** [comment]
Sorry about that, just fixed the issue and repushed to PyPI.  Try `pip install ifttt` again.

**Comment by davecoutts** [comment]
ifttt-0.3.0 installs perfectly now via pip. Thanks for the quick fix
